geo = {
    '102': 'Made ground',
    '104': 'Concrete',
    '201': 'CLAY',
    '202': 'Silty CLAY',
    '203': 'Sandy CLAY',
    '204': 'Gravelly CLAY',
    '205': 'Cobbly CLAY',
    '206': 'Bouldery CLAY',
    '207': 'Silty sandy CLAY',
    '208': 'Silty gravelly CLAY',
    '209': 'Silty cobbly CLAY',
    '210': 'Silty bouldery CLAY',
    '211': 'Silty sandy gravelly CLAY',
    '212': 'Silty sandy cobbly CLAY',
    '213': 'Silty sandy bouldery CLAY',
    '214': 'Silty sandy gravely cobbly CLAY',
    '215': 'Silty sandy gravelly boulder CLAY',
    '216': 'Silty sandy gravelly cobbly boulder CLAY',
    '217': 'Silty sandy organic CLAY',
    '218': 'Silty sandy gravelly organic CLAY',
    '219': 'Silty organic CLAY',
    '220': 'Sandy gravelly CLAY',
    '222': 'Sandy cobbly CLAY',
    '223': 'Sandy bouldery CLAY',
    '224': 'Sandy gravelly cobbly CLAY',
    '225': 'Sandy gravelly bouldery CLAY',
    '226': 'Sandy gravelly cobbly bouldery CLAY',
    '227': 'Sandy organic CLAY',
    '228': 'Sandy gravelly organic CLAY',
    '229': 'Organic CLAY',
    '301': 'SILT',
    '302': 'Clay / Silt',
    '303': 'Sandy SILT',
    '304': 'Gravelly SILT',
    '305': 'Organic SILT',
    '310': 'Sandy gravelly SILT',
    '314': 'Clayey sandy gravelly organic cobbly SILT',
    '316': 'Sandy cobbly SILT',
    '317': 'Sandy bouldery SILT',
    '318': 'Sandy organic SILT',
    '319': 'Sandy gravelly organic SILT',
    '320': 'Sandy gravelly cobbly SILT',
    '321': 'Sandy gravelly organic cobbly SILT',
    '322': 'Gravelly cobbly SILT',
    '323': 'Gravelly bouldery SILT',
    '324': 'Gravelly organic SILT',
    '325': 'Gravelly organic cobbly SILT',
    '326': 'Cobbly SILT',
    '327': 'Cobbly bouldery SILT',
    '328': 'Organic cobbly SILT',
    '331': 'Bouldery SILT',
    '401': 'SAND',
    '402': 'Clayey SAND',
    '403': 'Silty SAND',
    '404': 'Gravelly SAND',
    '405': 'Cobbly SAND',
    '406': 'Bouldery SAND',
    '410': 'Clayey gravelly SAND',
    '411': 'Clayey gravelly cobbly SAND',
    '412': 'Silty gravelly SAND',
    '413': 'Silty gravelly cobbly SAND',
    '414': 'Silty gravelly cobbly bouldery SAND',
    '415': 'Gravelly cobbly SAND',
    '416': 'Gravelly cobbly bouldery SAND',
    '417': 'Gravelly bouldery SAND',
    '418': 'Cobbly bouldery SAND',
    '430': 'SAND and GRAVEL',
    '431': 'Organic SAND',
    '433': 'Silty organic SAND',
    '434': 'Gravelly organic SAND',
    '435': 'Cobbly organic SAND',
    '436': 'Bouldery organic SAND',
    '501': 'GRAVEL',
    '502': 'Clayey GRAVEL',
    '503': 'Silty GRAVEL',
    '504': 'Sandy GRAVEL',
    '505': 'Organic GRAVEL',
    '506': 'Cobbly GRAVEL',
    '507': 'Bouldery GRAVEL',
    '509': 'Clayey sandy GRAVEL',
    '510': 'Clayey cobbly GRAVEL',
    '511': 'Clayey bouldery GRAVEL',
    '512': 'Clayey organic GRAVEL',
    '517': 'Clayey sandy organic GRAVEL',
    '520': 'Silty sandy GRAVEL',
    '521': 'Silty cobbly GRAVEL',
    '522': 'Silty bouldery GRAVEL',
    '523': 'Silty organic GRAVEL',
    '524': 'Silty organic sandy GRAVEL',
    '525': 'Sandy cobbly GRAVEL',
    '526': 'Sandy bouldery GRAVEL',
    '527': 'Sandy organic GRAVEL',
    '528': 'Silty sandy cobbly GRAVEL',
    '601': 'PEAT',
    '602': 'Clayey PEAT',
    '603': 'Silty PEAT',
    '604': 'Sandy PEAT',
    '605': 'Gravelly PEAT',
    '606': 'Cobbly PEAT',
    '608': 'Clayey sandy PEAT',
    '609': 'Clayey gravelly PEAT',
    '612': 'Silty sandy PEAT',
    '613': 'Silty sandy gravelly PEAT',
    '614': 'Sandy gravelly PEAT',
    '701': 'COBBLES',
    '702': 'Clayey COBBLES',
    '703': 'Silty COBBLES',
    '704': 'Sandy COBBLES',
    '705': 'Gravelly COBBLES',
    '706': 'Organic COBBLES',
    '708': 'Clayey sandy COBBLES',
    '709': 'Clayey gravelly COBBLES',
    '713': 'Silty sandy COBBLES',
    '714': 'Silty gravelly COBBLES',
    '715': 'Silty organic COBBLES',
    '716': 'Silty gravelly sandy COBBLES',
    '717': 'Silty sandy organic COBBLES',
    '718': 'Silty sandy gravelly organic COBBLES',
    '719': 'Sandy gravelly COBBLES',
    '720': 'Sandy organic COBBLES',
    '721': 'Gravelly organic COBBLES',
    '725': 'COBBLES and BOULDERS',
    '730': 'BOULDERS',
    '731': 'Gravelly cobbley BOULDERS',
    '801': 'MUDSTONE',
    '802': 'SILTSTONE',
    '803': 'SANDSTONE',
    '804': 'LIMESTONE',
    '805': 'CHALK',
    '806': 'COAL',
    '807': 'BRECCIA',
    '808': 'CONGLOMERATE',
    '809': 'Fine grained IGNEOUS',
    '810': 'Medium grained IGNEOUS',
    '811': 'Coarse grained IGNEOUS',
    '812': 'Fine grained METAMORPHIC',
    '813': 'Coarse grained METAMORPHIC',
    '814': 'Medium grained METAMORPHIC',
    '815': 'Pyroclastic (volcanic ash)',
    '816': 'Gypsum, Rocksalt',
    '817': 'Shale',
    '999': 'VOID',
    'ASPHALT': 'Asphalt',
    'BASALT': 'Basalt',
    'BEDROCK': 'Bedrock',
    'BLDRCBBL': 'Boulders and cobbles',
    'BRECCIA': 'Breccia',
    'CALCARENITE': 'CALCARENITE',
    'CALCILUTITE': 'CALCILUTITE',
    'CALCISILTITE': 'CALCISILTITE',
    'CAVITY': 'CAVITY',
    'CH': 'USCS High Plasticity Clay',
    'CHALK': 'Chalk',
    'CL': 'USCS Low Plasticity Clay',
    'CLAYSTONE': 'CLAYSTONE'
}